# Generated by Django 5.2.10 on 2026-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='depart_from',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
